### ISSUE TITLE
Auto Hash User Parameters (SHA-256)

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/snapchat-tag#14]
I was testing the Snapchat Tags and I've got the following error message:

`{"status":"INVALID","event":1,"errors":{"codes":["506"],"error_msgs":["Hash all user parameters as SHA256, except for client user agent, click ID, and browser ID. Any other user parameters that are not hashed are automatically rejected."]}}`

Can you please improve the Tag template so that these User parameters are auto-hashed?

So similar to how the Facebook or TikTok tag templates are working now.

Documentation: https://docs.snap.com/api/marketing-api/Conversions-API/Parameters

**Comment by alexgarciab** [comment]
Any plans to implement this soon? @kHorozhanov

It is the only tag, out of the multiple I have tested that do not hash the user data by default.

**Comment by derrickhnguyen** [comment]
I found the issue.

It is this line - https://github.com/stape-io/snapchat-tag/blob/master/template.tpl#L980

The set the hash value in the incorrect place :D

**Comment by Bukashk0zzz** [comment]
Issue fixed.

**Comment by alexgarciab** [comment]
@Bukashk0zzz I am still getting this error with the new version:

`{"status":"INVALID","event":1,"errors":{"codes":["506"],"error_msgs":["Hash all user parameters as SHA256, except for client user agent, click ID, and browser ID. Any other user parameters that are not hashed are automatically rejected."]}}`

**Comment by kHorozhanov** [comment]
@alexgarciab Sorry, my mistake. I have published a fully updated .tpl file. 
It should work correctly with the next update.
