### ISSUE TITLE
Test server events - Not working (V3)

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/snapchat-tag#17]
For Snapchat Ads API V3 the "Test server events" feature is not working. These are the instructions:

![testing](https://github.com/stape-io/snapchat-tag/assets/6924386/ae8539dd-6572-48e9-8888-aef6ded4b31b)

I believe the tag has the old testing method (V2) where a "Test Event Code" was needed.

In V3, for testing, sending the request to the same endpoint as the normal conversion, plus adding the **/validate** string at the end of the URL would do the work.

So instead of having a field in the "Server Parameters" in the tag, it should probably be a checkbox like "Enable testing".

**Comment by kHorozhanov** [comment]
Hi @alexgarciab, thank you for reaching out!
The Snapchat tag already supports validating requests, as you described above.
<img width="631" alt="Screenshot 2024-07-09 at 17 47 43" src="https://github.com/stape-io/snapchat-tag/assets/15924598/d37426ea-6a0b-4855-82d4-92cd9b3bba21">

Also, [here](https://docs.snap.com/api/marketing-api/Conversions-API/Parameters#server-parameters) is the reference to the Snapchat conversion API where the `test_event_code` param was described.

**Comment by alexgarciab** [comment]
Ok, my bad. I didn't see that option. As in every tag the name is different, then I missed it in Snapchat Tag. For example:

- Pinterest > Test request
- Reddit > Test Mode
- Snapchat > Validate CAPI events

But only using "test_event_code", it is not showing any test events in Snapchat "Test server events" screen.

**Comment by kHorozhanov** [comment]
@alexgarciab thank you for reporting this problem.
In all mentioned tags, the names will be updated to `Test Mode`.
About the test_event_code parameter - can you please ask someone from Snapchat about it?
Because it still exists in official API docs https://docs.snap.com/api/marketing-api/Conversions-API/Parameters#server-parameters
Thank you!

**Comment by alexgarciab** [comment]
Great! thanks for updating the corresponding tags.

As for the "test_event_code" parameter, I know from experience that they documentation of Snapchat V3 API has not been the best I've seen out there. They had some inconsistencies in the documentation. I believe they took Snapchat V2 API documentation as a base, but forgot to remove things that are no longer working.

You can close this issue @kHorozhanov
